development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://default:6c2aa67f5f1149fe7752158c82a78@fly-our-chat-redis.upstash.io
  channel_prefix: chatroom_production
